name: build

on:
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

env:
  COINCURVE_UPSTREAM_REF: 1ad5185cd42c0636104129fcc9f6a4bf9c67cc40
  COINCURVE_IGNORE_SYSTEM_LIB: '1'
  # Only 'SHARED' is recognized, any other string means 'not SHARED'
  COINCURVE_SECP256K1_BUILD: 'STATIC'
  CIBW_ENVIRONMENT_PASS_LINUX: >
    COINCURVE_UPSTREAM_REF
    COINCURVE_IGNORE_SYSTEM_LIB
    COINCURVE_SECP256K1_BUILD
  CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
  CIBW_BEFORE_ALL_MACOS: ./.github/scripts/install-macos-build-deps.sh
  CIBW_TEST_REQUIRES: pytest pytest-benchmark
  CIBW_TEST_COMMAND: >
    python -c
    "from coincurve import PrivateKey;
    a=PrivateKey();
    b=PrivateKey();
    assert a.ecdh(b.public_key.format())==b.ecdh(a.public_key.format())
    " &&
    python -m pytest {project}
  CIBW_TEST_SKIP: "*-macosx_arm64"
  CIBW_SKIP: >
      pp*

jobs:
  test:
    name: Test latest Python
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.12'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Upgrade Python packaging tools
      run: pip install --upgrade pip setuptools wheel

    - name: Show runner information
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: ./.github/scripts/install-test-deps.sh

    - name: Check style and typing
      run: tox -e lint,typing

    - name: Run tests
      run: tox -e ${PYTHON_VERSION}

    - name: Run benchmarks
      run: tox -e bench

    - name: Upload coverage
      run: codecov -X gcov

  test-with-libsecp256k1:
    name: Test Conda libsecp256k1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    env:
      PYTHON_VERSION: '3.12'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: ./.github/scripts/install-test-deps.sh

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: test-conda
        python-version: ${{ env.PYTHON_VERSION }}
        auto-activate-base: false

    - name: Install dependencies
      run: conda install requests tox-conda libsecp256k1 -c conda-forge

    - name: Run tests
      run: tox -e ${{ env.PYTHON_VERSION }}

    - name: Run benchmarks
      run: tox -e bench

  linux-wheels-standard:
    name: Build Linux wheels
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        CIBW_BUILD: 'cp38-manylinux_x86_64'
        CIBW_BUILD_VERBOSITY: 1

  macos-wheels-x86-64:
    name: Build macOS wheels
    needs:
    - test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_MACOS: x86_64

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_MACOS: x86_64
        COINCURVE_SECP256K1_BUILD: 'SHARED'


  macos-wheels-arm:
    name: Build macOS wheels for ARM
    needs:
    - test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_MACOS: arm64
        COINCURVE_CROSS_HOST: 'arm64'

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_MACOS: arm64
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        COINCURVE_CROSS_HOST: 'arm64'


  macos-wheels-arm-beta:
    name: Build macOS wheels for ARM (Native
    needs:
    - test
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_MACOS: arm64

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        CIBW_ARCHS_MACOS: arm64


  windows-wheels-conda-x86_64:
    name: Build Windows (CONDA) wheels AMD64
    needs:
    - test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ENVIRONMENT:
            COINCURVE_IGNORE_SYSTEM_LIB="0"
            COINCURVE_UPSTREAM_REF="__no_tag__"
            COINCURVE_SECP256K1_BUILD='SHARED'
        CIBW_BUILD: "cp312-win_amd64"
        CIBW_ARCHS_WINDOWS: "AMD64"
        CIBW_BEFORE_ALL: >
            conda install -c conda-forge pkg-config libsecp256k1 &&
            vswhere /latest /find regsvr32.exe &&
            regsvr32 /s %CONDA_PREFIX%\Library\bin\libsecp256k1-2.dll
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_REQUIRES: pytest pytest-benchmark
        CIBW_TEST_COMMAND: >
            conda install -c conda-forge libsecp256k1 &&
            pkg-config --cflags --libs --dont-define-prefix libsecp256k1 &&
            set PATH=%PATH%;%CONDA_PREFIX%\Library\bin &&
            regsvr32 /s %CONDA_PREFIX%\Library\bin\libsecp256k1-2.dll &&
            python -m pip list -v &&
            python -c
            "from coincurve import PrivateKey;
            a=PrivateKey();
            b=PrivateKey();
            assert a.ecdh(b.public_key.format())==b.ecdh(a.public_key.format())
            "
        # This fails due to the way tests/ is installed by cibuildwheel
        # The way I worked around it is to refactor the tests with conftest.py
        # defining samples.py items as fixtures
            # pytest {project}


  windows-wheels-x86_64:
    name: Build Windows wheels AMD64
    needs:
    - test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_WINDOWS: "AMD64"
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        CIBW_ARCHS_WINDOWS: "AMD64"
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite


  windows-wheels-x86:
    name: Build Windows wheels x86
    needs:
    - test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_CROSS_HOST: "x86"
        CIBW_ARCHS_WINDOWS: "x86"
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        COINCURVE_CROSS_HOST: "x86"
        CIBW_ARCHS_WINDOWS: "x86"
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite


  windows-wheels-arm64:
    name: Build Windows wheels for ARM64
    needs:
    - test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_CROSS_HOST: "arm64"
        CIBW_ARCHS_WINDOWS: "ARM64"
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

    - name: Build SHARED wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        COINCURVE_SECP256K1_BUILD: 'SHARED'
        COINCURVE_CROSS_HOST: "arm64"
        CIBW_ARCHS_WINDOWS: "ARM64"
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28 pkgconfiglite


  sdist:
    name: Build source distribution
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: python -m pip install build

    - name: Build source distribution
      run: python -m build --sdist

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  linux-wheels-arm:
    name: Build Linux wheels for ARM
    needs:
    - test
    runs-on: ubuntu-20.04
    if: >
      github.event_name == 'push'
      &&
      (github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags'))

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_ARCHS_LINUX: aarch64

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - linux-wheels-standard
    - macos-wheels-x86-64
    - macos-wheels-arm
    - sdist
    - windows-wheels-x86_64
    - windows-wheels-x86
    - windows-wheels-arm64
    - linux-wheels-arm
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
